# ==========================================
# CONFIGURACIÓN GENERAL (SIDC) [cite: 8]
# ==========================================
spring.application.name=SIDC-Backend

# Indicar a Spring que use el perfil 'local' además del default
spring.profiles.include=local

# Configuración de JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Configuración de Gmail (Servidor)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Logging para ver errores de base de datos detallados
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE