# src/main/resources/application-local.properties
# 1. Desactivar el umbral de sentencias preparadas para evitar el error "S_2"
spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:6543/postgres?prepareThreshold=0

# 2. Forzar a Hibernate a no usar el cache de sentencias a nivel de sesión
spring.jpa.properties.hibernate.prepare_threshold=0
spring.datasource.username=postgres.wqqtwcaurpojopcaftkt
spring.datasource.password=e0WNMmtC4xpL6Bxw
spring.mail.username=nestorutog@gmail.com
spring.mail.password=zjjndszpmqzagihg