# src/main/resources/application-local.properties
spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.wqqtwcaurpojopcaftkt
spring.datasource.password=e0WNMmtC4xpL6Bxw
spring.mail.username=nestorutog@gmail.com
spring.mail.password=zjjndszpmqzagihg